apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata: 
  name: k8s-lefty23-coza-tls
spec: 
  secretName: k8s-lefty23-coza-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: lefty23.co.za
  dnsNames:
    - lefty23.co.za
    - www.lefty23.co.za
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - lefty23.co.za
          - www.lefty23.co.za